#公共配置
spring:
  profiles:
    active: dev
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always